### ISSUE TITLE
Dead project

### ISSUE THREAD

**Issue by watzon** [nim-appkit/omnilog#1]
This looks like an awesome logging library, but I don't see any activity in the past couple years. Is this project still being supported?

**Comment by theduke** [comment]
@watzon no it's not maintained anymore.

I have not done any work with nim for two years, and am unlikely to pick it up again.

If anyone was interested in taking over, I'd be more than happy to hand over the repo.

**Comment by watzon** [comment]
@theduke I'd be happy to take it from ya. It seems like a great logger

**Comment by watzon** [comment]
In fact, if you're not going to be working in nim anymore I'd happily take the whole `nim-appkit` off your hands
